# Generated by Django 4.0.5 on 2022-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_database_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='movie_poster',
            field=models.URLField(),
        ),
    ]
